name: Logo Requests
description: For requesting logos
title: "[LOGO REQUEST] INSERT LOGO NAME HERE"
labels: ["Logo Request"]
assignees: Aikoyori
body:
  - type: markdown
    attributes:
      value: |
        # Thanks for your interest!
        ## Please READ before submitting or YOUR ISSUE WILL BE CLOSED.

        Please provide the following information and answer the questions correctly:
  - type : input
    id: product-name
    attributes:
      label: Product Name
      description: The product you want the logo to be made
      placeholder: Acme Explosive Eggs
    validations:
      required: true
  - type : input
    id: product-link
    attributes:
      label: Product Link
      description: The link to the product
      placeholder: https://example.com
    validations:
      required: true
  - type : textarea
    id: additional-info
    attributes:
      label: Other information
      description: Describe the product and the logo you want
      placeholder: The logo should be made with with Acme color scheme.
    validations:
      required: false
  - type: checkboxes 
    id: verification1
    attributes:
      label: Select the following
      description: Please select **ALL** of the following that sounds positive.
      options:
        - label: "Someone else has not requested this and I have not checked that that is the case because I am too lazy and I just want to spam these request to keep the guy busy."
        - label: "I am genuinely so tired of reading please give me a break I literally thought this would be a no-brainer process but suddenly I am doing an eight-choice quiz about my life."
        - label: "I have read and actually let out my inner voice won and then I submitted the issue anyway because I think it's so funny seeing people suffer from my actions."
        - label: "Imagine if a fly landed on your face, you would actually try to get it away, right? That's literally how you are doing the deed and I appreciate that you will do this."
        - label: "Stop yapping about everything I just want to patiently wait for my logo to be eventually done thought what is going to make me mad is that more people don't understand this."
        - label: "I love the author of this repository so much I could practically harass someone for it and I will do it again on any repository that makes it hard for me."
        - label: "I would really like to know how you are doing this all with just some time left on your hand. This shit genuinely sucks and you deserves better than getting dupes."
        - label: "Please go rid yourself of other tasks and pay attention to your real tasks much less do this because you have a life to live but this is cool!"
        - label: "I hate this thing so much I do not want to see it ever again but could you please do logos for me I will literally cry myself to sleep about it."
        - label: "Stop slacking off and get to work you lazy piece of worthy person please do not take your time on this project and focus on your real work."
  - type: checkboxes
    id: agreement
    attributes:
      label: The following is required to submit this issue
      description: By submitting this issue, you agree that these logos will be made available under the project's license and that you have checked if the logo is already available or already requested.
      options:
        - label: I agree that the logo will be made available under the project's license
          required: true
        - label: Select this to have your issue immediately closed (1)
          required: false
        - label: Select this no have your issue immediately closed (2)
          required: false
        - label: Select this to have your issue immediately closed (3)
          required: false
        - label: Select this no have your issue immediately closed (4)
          required: false
        - label: Select this no have your issue immediately closed (5)
          required: false
        - label: I have checked that I am not making a duplicate request (1)
          required: false
        - label: I have checked that I am not making a duplicate request (2)
          required: false
        - label: I have checked that I am not making a duplicate request (3)
          required: false
        - label: I have checked that I am yes making a duplicate request (4)
          required: false
        - label: I have checked that I am not making a duplicate request (5)
          required: false
        - label: I genuinely did not give a single damn if this gets rejected because I did not read any single thing and just blindly click every checkbox.
          required: false
        - label: If this turns out to be a duplicate, I agree that I will be burned at stake and publicly shamed until the project maintainer deems enough
          required: true
        - label: If this turns out to be a duplicate, I agree that I will have my access from the repository revoked.
          required: true